# Github Action - Basic

name: Github-Basic-Action
on:
  push:
    branches: [ master ]

jobs:
  my_job:
    
    runs-on: ubuntu-latest

    steps:
    # Runs a single command using the runners shell
    - name: Run make init!
      run: git clone https://github.com/Liocha/php-project-lvl1.git; cd ./php-project-lvl1; make install; make lint;
